// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.shopzilla.perfvis.data;

import com.shopzilla.perfvis.data.WebappDataDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WebappDataIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WebappDataIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WebappDataIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: WebappDataIntegrationTest: @Transactional;
    
    @Autowired
    private WebappDataDataOnDemand WebappDataIntegrationTest.dod;
    
    @Test
    public void WebappDataIntegrationTest.testCountWebappDatas() {
        org.junit.Assert.assertNotNull("Data on demand for 'WebappData' failed to initialize correctly", dod.getRandomWebappData());
        long count = com.shopzilla.perfvis.data.WebappData.countWebappDatas();
        org.junit.Assert.assertTrue("Counter for 'WebappData' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WebappDataIntegrationTest.testFindWebappData() {
        com.shopzilla.perfvis.data.WebappData obj = dod.getRandomWebappData();
        org.junit.Assert.assertNotNull("Data on demand for 'WebappData' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'WebappData' failed to provide an identifier", id);
        obj = com.shopzilla.perfvis.data.WebappData.findWebappData(id);
        org.junit.Assert.assertNotNull("Find method for 'WebappData' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'WebappData' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WebappDataIntegrationTest.testFindAllWebappDatas() {
        org.junit.Assert.assertNotNull("Data on demand for 'WebappData' failed to initialize correctly", dod.getRandomWebappData());
        long count = com.shopzilla.perfvis.data.WebappData.countWebappDatas();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'WebappData', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.shopzilla.perfvis.data.WebappData> result = com.shopzilla.perfvis.data.WebappData.findAllWebappDatas();
        org.junit.Assert.assertNotNull("Find all method for 'WebappData' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'WebappData' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WebappDataIntegrationTest.testFindWebappDataEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'WebappData' failed to initialize correctly", dod.getRandomWebappData());
        long count = com.shopzilla.perfvis.data.WebappData.countWebappDatas();
        if (count > 20) count = 20;
        java.util.List<com.shopzilla.perfvis.data.WebappData> result = com.shopzilla.perfvis.data.WebappData.findWebappDataEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'WebappData' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'WebappData' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WebappDataIntegrationTest.testFlush() {
        com.shopzilla.perfvis.data.WebappData obj = dod.getRandomWebappData();
        org.junit.Assert.assertNotNull("Data on demand for 'WebappData' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'WebappData' failed to provide an identifier", id);
        obj = com.shopzilla.perfvis.data.WebappData.findWebappData(id);
        org.junit.Assert.assertNotNull("Find method for 'WebappData' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWebappData(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'WebappData' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WebappDataIntegrationTest.testMerge() {
        com.shopzilla.perfvis.data.WebappData obj = dod.getRandomWebappData();
        org.junit.Assert.assertNotNull("Data on demand for 'WebappData' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'WebappData' failed to provide an identifier", id);
        obj = com.shopzilla.perfvis.data.WebappData.findWebappData(id);
        boolean modified =  dod.modifyWebappData(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.shopzilla.perfvis.data.WebappData merged = (com.shopzilla.perfvis.data.WebappData) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'WebappData' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WebappDataIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'WebappData' failed to initialize correctly", dod.getRandomWebappData());
        com.shopzilla.perfvis.data.WebappData obj = dod.getNewTransientWebappData(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'WebappData' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'WebappData' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'WebappData' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WebappDataIntegrationTest.testRemove() {
        com.shopzilla.perfvis.data.WebappData obj = dod.getRandomWebappData();
        org.junit.Assert.assertNotNull("Data on demand for 'WebappData' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'WebappData' failed to provide an identifier", id);
        obj = com.shopzilla.perfvis.data.WebappData.findWebappData(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'WebappData' with identifier '" + id + "'", com.shopzilla.perfvis.data.WebappData.findWebappData(id));
    }
    
}
